# application-dev.yml
app:
  default-role: user
db:
  username: dev_user
  password: dev_pass

spring:
  application:
    name: alertops

  datasource:
    url: jdbc:postgresql://ep-falling-snow-a1oq1a43-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_AKkZU1I7itaM
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

# psql ''